blank_issues_enabled: false
contact_links:
  - name: 🤔 Question 
    url: https://github.com/TheFizFactor/COMICERS/discussions/new
    about: Ask a question about Comicers 
  - name: 🔗 Extensions repository
    url: https://github.com/TheFizFactor/COMICERS-extensions/issues/new/choose
    about: Reports/requests for extensions should be opened in the extensions repository
  - name: 🖥️ Comicers website
    url: https://comicers.org
    about: Documentation for using Comicers
